shop/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('',views.index,name='index'),
    path('registro',views.registro,name='registro'),
    path('login',views.loginUsuario,name='login'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('carrito',views.carrito,name='carrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name="eliminarProductoCarrito"),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('pedido',views.pedido,name='pedido'),
    path('logout',views.logout_view,name='logout'),
    path('pagoexitosopaypal',views.pago_exitoso_paypal,name='pagoexitosopaypal')
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import DecimalField, IntegerField

from cloudinary.models import CloudinaryField

"""
para migrar modelos a base datos
python manage.py makemigrations
python manage.py migrate

"""
# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    stock = models.IntegerField(default=0)
    pub_date = models.DateTimeField('fecha registro')
    #imagen = models.ImageField(upload_to='productos',blank=True,null=True)
    imagen = CloudinaryField('image',default='')
    
    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    doc_ide = models.CharField(max_length=20,unique=True)
    direccion = models.CharField(max_length=200,blank=True)
    telefono = models.CharField(max_length=20,blank=True)
    
    def __str__(self):
        return self.usuario.first_name
    
class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha = models.DateField(auto_now=True)
    total = models.DecimalField(max_digits=10,decimal_places=2)
    estado = models.CharField(max_length=1,default='0')
    
    def __str__(self):
        return self.cliente.doc_ide
    
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = IntegerField(default=1)
    subtotal = DecimalField(max_digits=10,decimal_places=2)
    
    def __str__(self):
        return self.producto.nombre
    
    

tienda/forms.py
from django import forms

class ClienteForm(forms.Form):
    doc_ide = forms.CharField(label='DNI',max_length=20,required=True)
    nombres = forms.CharField(max_length=200,required=True)
    apellidos = forms.CharField(max_length=200,required=True)
    email = forms.EmailField(required=True)
    direccion = forms.CharField(widget=forms.Textarea,required=False)
    telefono = forms.CharField(max_length=20,required=False)
    usuario = forms.CharField(max_length=20,required=True)
    clave = forms.CharField(widget=forms.PasswordInput)
    
class UsuarioForm(forms.Form):
    usuario = forms.CharField(max_length=20,required=True)
    clave = forms.CharField(widget=forms.PasswordInput)

tienda/views.py
from django.shortcuts import render,redirect
from django.conf import settings

from .models import Producto,Cliente,Pedido,PedidoDetalle
from django.contrib.auth.models import User

#IMPORTANDO METODOS PARA AUTENTICACIÓN DE USUARIOS
from django.contrib.auth import authenticate,login,logout

from tienda.carrito import Cart
from tienda.forms import ClienteForm,UsuarioForm

from django.contrib.auth.decorators import login_required

#### PAYPAL ########
from paypal.standard.forms import PayPalPaymentsForm

# Create your views here.
def index(request):
    lista_productos = Producto.objects.all()
    print(settings.MEDIA_URL)
    context = {'lstProductos': lista_productos,'directorio_img':settings.MEDIA_URL}
    return render(request,'index.html',context)

def registro(request):
    frmCliente = ClienteForm()
    
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        frmNuevoCliente = ClienteForm(request.POST)
        # check whether it's valid:
        if frmNuevoCliente.is_valid():
            data = frmNuevoCliente.cleaned_data
            dataUsuario = data['usuario']
            dataPassword = data['clave']
            #creamos usuarios
            nuevoUsuario = User.objects.create_user(username=dataUsuario,password=dataPassword)
            
            nuevoUsuario.first_name = data['nombres']
            nuevoUsuario.last_name = data['apellidos']
            nuevoUsuario.email = data['email']
            nuevoUsuario.save()
            
            nuevoCliente = Cliente(usuario=nuevoUsuario)
            nuevoCliente.telefono = data['telefono']
            nuevoCliente.direccion = data['direccion']
            nuevoCliente.doc_ide = data['doc_ide']
            nuevoCliente.save()
            
            return render(request,'graciasRegistro.html')
            
    context = {
        'frmCliente':frmCliente
    }
    return render(request,'registroCliente.html',context)

def loginUsuario(request):
    frmUsuario = UsuarioForm()
    
    if request.method == 'POST':
        frmLogin = UsuarioForm(request.POST)
        
        if frmLogin.is_valid():
            data = frmLogin.cleaned_data
            dataUsuario = data['usuario']
            dataPassword = data['clave']
            
            loginUsuario = authenticate(request,username=dataUsuario,password=dataPassword)
            if loginUsuario is not None:
                print("ok")
                login(request,loginUsuario)
                return render(request,'cuenta.html')
            else:
                print("error")
                context = {
                    'form':frmUsuario,
                    'error':'datos erroneos'
                }
                return render(request,'login.html',context)
            
    
    context = {
        'form':frmUsuario
    }
    return render(request,'login.html',context)

def producto(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id) 
    #equivalente a : select * from producto where id = producto_id
    context = {
        "producto":objProducto
    }
    return render(request,'producto.html',context)

def agregarCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.add(objProducto,1)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def eliminarProductoCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.remove(objProducto)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def limpiarCarrito(request):
    CarritoProducto = Cart(request)
    CarritoProducto.clear()
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def carrito(request):
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def pedido(request):
    print(request.user.id)
    if request.user.id is not None:
        #SELECCIONAR EL USUARIO
        userPedido = User.objects.get(id=request.user.id)
        #SELECCIONAR EL CLIENTE
        try:
            clientePedido = Cliente.objects.get(usuario=userPedido)
            
            nuevoPedido = Pedido()
            nuevoPedido.cliente = clientePedido
            nuevoPedido.total = 0
            nuevoPedido.save()
            
            pedidoCart = request.session.get("cart")
            print(pedidoCart)
            totalPedido = 0
            lstDetallePedidos = []
            for key,value in pedidoCart.items():
                detalle = PedidoDetalle()
                detalle.pedido = nuevoPedido
                detalleProducto = Producto.objects.get(id=value["producto_id"])
                detalle.producto = detalleProducto
                detalle.cantidad = int(value["cantidad"])
                detalle.subtotal = float(value["total"])
                detalle.save()
                lstDetallePedidos.append(detalle)
                totalPedido += float(value["total"])
            
            nuevoPedido.total = totalPedido
            nuevoPedido.save()
            ###### PARA PAGO PAYPAL####
            request.session['paypal_pid'] = nuevoPedido.id
            host = request.get_host()
            paypal_datos = {
                'business': settings.PAYPAL_RECEIVER_EMAIL,
                'amount': nuevoPedido.total,
                'item_name': 'PEDIDO #' + str(nuevoPedido.id),
                'invoice': str(nuevoPedido.id),
                'notify_url': 'http://' + host + '/' + 'paypal-ipn',
                'return_url':'http://' + host + '/pagoexitosopaypal'
            }
            formPedidoPaypal = PayPalPaymentsForm(initial=paypal_datos)
            context = {
                'pedido' : nuevoPedido,
                'detalles':lstDetallePedidos,
                'formpaypal': formPedidoPaypal
            }
            return render(request,'pedido.html',context)
        except:
            return redirect('/login')
    else:
        return redirect('/login')
    
@login_required
def logout_view(request):
    """Logout a user."""
    logout(request)
    return redirect('/login')

################# PAYPAL ######################3
def pago_exitoso_paypal(request):
    pedido_id = request.session.get('paypal_pid')
    pedido = Pedido.objects.get(id=pedido_id)
    pedido.estado = '1'
    pedido.save()
    context = {
     'pedido': pedido   
    }
    return render(request,'pagoexitosopaypal.html',context)
    
            
    

tienda/templates/carrito.html
{% extends "layout.html" %}
{% block content %}
<div class="container px-3 my-5 clearfix">
    <!-- Shopping cart table -->
    <div class="card">
        <div class="card-header">
            <h2>Carrito de Compras</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="min-width: 400px;">Producto</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Precio</th>
                    <th class="text-center py-3 px-4" style="width: 120px;">Cantidad</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Total</th>
                    <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                  </tr>
                </thead>
                <tbody>
                {% for key,value in request.session.cart.items %}
                  <tr>
                    <td class="p-4">
                      <div class="media align-items-center">
                        <img src="{{ value.imagen }}" width="100px" class="d-block ui-w-40 ui-bordered mr-4" alt="">
                        <div class="media-body">
                          <a href="{% url 'tienda:producto' value.producto_id %}" class="d-block text-dark">{{ value.nombre }}</a>
                        </div>
                      </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ value.precio }}</td>
                    <td class="align-middle p-4"><input type="text" class="form-control text-center" value="{{ value.cantidad }}"></td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ value.total }}</td>
                    <td class="text-center align-middle px-0"><a href="{% url 'tienda:eliminarProductoCarrito' value.producto_id %}" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
                
            <!-- / Shopping cart table -->     
            <div class="float-right">
              <a class="btn btn-primary" href="{% url 'tienda:index' %}" role="button">REGRESAR</a>
              <a class="btn btn-primary" href="{% url 'tienda:limpiarCarrito' %}" role="button">LIMPIAR</a>
              <a class="btn btn-primary" href="{% url 'tienda:pedido' %}" role="button">REALIZAR PEDIDO</a>
              
            </div>
          </div>
      </div>
  </div>
{% endblock %}

tienda/templates/cuenta.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h2>Bienvenido(a) : {{ request.user.first_name  }} - {{ request.user.last_name  }}</h2>
</div>
{% endblock %}

tienda/templates/graciasRegistro.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h2>Registro Exitoso</h2>
</div>
{% endblock %}

tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for producto in lstProductos %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{ producto.imagen.url }}" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                <!-- Product price-->
                                S/. {{producto.precio}}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'tienda:producto' producto.id %}">Ver mas</a></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

tienda/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>TIENDA TECH</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'tienda:index' %}">TIENDA TECH</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'tienda:registro' %}">Registro</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">Productos</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <a href="{% url 'tienda:login' %}" class="btn btn-primary">LOGIN</a>
                    <a href="{% url 'tienda:logout' %}" class="btn btn-primary">LOGOUT</a>
                    <a href="{% url 'tienda:carrito' %}">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Carrito
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </a>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">TIENDA TECH</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Tienda de Tecnología</p>
                </div>
            </div>
        </header>
        <!-- Section-->
       {% block content %}
       {% endblock %}
       <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

tienda/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif%}
    <h2>LOGIN DE USUARIO</h2>
    {{ form.non_field_errors }}
    <form method="POST" action="{% url 'tienda:login' %}">
        {% csrf_token %}
        
        <div class="form-group">
            {{ form.usuario.errors }}
            <label for="{{ form.usuario.id_for_label }}">Usuario:</label>
            {{ form.usuario }}
        </div>
        <div class="form-group">
            {{ form.clave.errors }}
            <label for="{{ form.clave.id_for_label }}">Password:</label>
            {{ form.clave }}
        </div>
    
    
        <button class="btn btn-primary btn-block mt-5" type="submit">LOGIN</button>
    
    </form>
</div>
{% endblock %}

tienda/templates/pagoexitosopaypal.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            PAGO EXITOSO- GRACIAS POR TU PEDIDO
        </div>
        <div class="card-body">
          <h5 class="card-title">ESTIMADO(a)  {{ request.user.first_name  }} - {{ request.user.last_name  }} </h5>
          <p class="card-text">SU PEDIDO POR  : {{ pedido.total }} FUE PROCESADO CON EXITO</p>
        </div>
      </div>
</div>
{% endblock %}

tienda/templates/pedido.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            PEDIDO FUE REALIZADO CON EXITO
        </div>
        <div class="card-body">
          <h5 class="card-title">CLIENTE : {{ request.user.first_name  }} - {{ request.user.last_name  }} </h5>
          <p class="card-text">TOTAL PEDIDO : {{ pedido.total }}</p>
          {{ formpaypal.render }}
        </div>
      </div>
</div>
{% endblock %}

tienda/templates/producto.html
{% extends "layout.html" %}
{% block content %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ producto.imagen.url }}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1"></div>
                <h1 class="display-5 fw-bolder">{{ producto.nombre }}</h1>
                <div class="fs-5 mb-5">
                    <span>S/. {{ producto.precio }}</span>
                </div>
                <p class="lead"></p>
                <div class="d-flex">
                    <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                    <a class="btn btn-primary" href="{% url 'tienda:agregarCarrito' producto.id %}" role="button">Agregar Carrito</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

tienda/templates/registroCliente.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h2>Registro de nuevo Cliente</h2>
    <form 
    action="{% url 'tienda:registro' %}" 
    method="post">
        {% csrf_token %}
        {{ frmCliente.as_p }}
        <input type="submit" 
        value="Registrarse">
    </form>
</div>
{% endblock %}